### ISSUE TITLE
ERROR in app: Exception on /rl [GET]

### ISSUE THREAD

**Issue by Busindre** [boxug/trape#11]
Hi!

I have some problems with Trape in Linux, is a bug?

Python Version: Python 2.7.14 (default, Sep 20 2017, 01:25:59).

```
python2 trape.py -url https://www.google.com -p 80

...
	+--=[ Lure for the victims: http://127.0.0.1:80/rl
	+--=[ Control Panel Link: http://127.0.0.1:80/s34d7e7
	+--=[ Your Access key: 4eb9fb76ae4b4f40f3946671


[>] Start time: 2017-11-07 - 20:20:57
[¡] Waiting for the victims to fall...

[2017-11-07 20:21:14,190] ERROR in app: Exception on /rl [GET]
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/busi/trape/core/victim.py", line 34, in homeVictim
    html = victim_inject_code(opener.open(trape.url_to_clone).read(), 'lure')
  File "/usr/lib/python2.7/urllib2.py", line 421, in open
    protocol = req.get_type()
  File "/usr/lib/python2.7/urllib2.py", line 283, in get_type
    raise ValueError, "unknown url type: %s" % self.__original
ValueError: unknown url type: rl
```

```
 pip2 install -r requirements.txt 
Requirement already satisfied: Flask==0.12.2 in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 1))
Collecting Flask-Login==0.4.0 (from -r requirements.txt (line 2))
  Using cached Flask_Login-0.4.0-py2.py3-none-any.whl
Collecting Flask-Session==0.3.1 (from -r requirements.txt (line 3))
  Using cached Flask_Session-0.3.1-py2.py3-none-any.whl
Requirement already satisfied: Flask_SocketIO in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 4))
Requirement already satisfied: itsdangerous==0.24 in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 5))
Collecting Jinja2==2.7.3 (from -r requirements.txt (line 6))
  Using cached Jinja2-2.7.3.tar.gz
Collecting MarkupSafe==0.23 (from -r requirements.txt (line 7))
  Using cached MarkupSafe-0.23.tar.gz
Requirement already satisfied: python-engineio in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 8))
Requirement already satisfied: python-socketio in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 9))
Collecting six==1.9.0 (from -r requirements.txt (line 10))
  Using cached six-1.9.0-py2.py3-none-any.whl
Collecting Werkzeug==0.12.2 (from -r requirements.txt (line 11))
  Using cached Werkzeug-0.12.2-py2.py3-none-any.whl
Requirement already satisfied: click>=2.0 in /usr/lib/python2.7/site-packages (from Flask==0.12.2->-r requirements.txt (line 1))
Installing collected packages: Flask-Login, Flask-Session, MarkupSafe, Jinja2, six, Werkzeug
  Found existing installation: MarkupSafe 1.0
    Uninstalling MarkupSafe-1.0:
      Successfully uninstalled MarkupSafe-1.0
  Running setup.py install for MarkupSafe ... done
  Found existing installation: Jinja2 2.9.6
    Uninstalling Jinja2-2.9.6:
      Successfully uninstalled Jinja2-2.9.6
  Running setup.py install for Jinja2 ... done
  Found existing installation: six 1.11.0
    Uninstalling six-1.11.0:
      Successfully uninstalled six-1.11.0
  Found existing installation: Werkzeug 0.12.2.dev0
    Uninstalling Werkzeug-0.12.2.dev0:
      Successfully uninstalled Werkzeug-0.12.2.dev0
Successfully installed Flask-Login-0.4.0 Flask-Session-0.3.1 Jinja2-2.7.3 MarkupSafe-0.23 Werkzeug-0.12.2 six-1.9.0
```

Regards!

**Comment by st4nn** [comment]
Hi, thanks for writing,

Isn't an issue, the problem is you arent especifing and valid address, you need run trape with a valid lure url, for example: python trape.py -p 8080 -u **HTTPS://GOOGLE.COM**, because trape server can't reach _rl_

Happy hack

**Comment by Busindre** [comment]
Hi.

No, I've already tried many different combinations and it does not work :(.
```
python2 trape.py -p 80 -url https://google.com
```
Any other idea?

**Comment by st4nn** [comment]
@Busindre `python2 trape.py -p 80 -u https://google.com` just **-u**

Test and please let me know if works

**Comment by Busindre** [comment]
Oh goth, sorry, my fault, "--url" or "-u". I'm stunned today. You can delete the "issue" .

Thank you very much!
