### ISSUE TITLE
trape error  in kali

### ISSUE THREAD

**Issue by shubhampuri240** [boxug/trape#327]
python trape.py -h

_Traceback (most recent call last):
  File "trape.py", line 23, in <module>
    from core.utils import utils                  #
  File "/home/livinglegend/trape/core/utils.py", line 21, in <module>
    import requests, json
ImportError: No module named requests
_

  can some please help in kali linux

**Comment by vral-parmar** [comment]
pip3 install requests

**Comment by vral-parmar** [comment]
walways run trap with sudo and install all the dependancy using sudo only.

**Comment by Tato418** [comment]
pip3 install -r requirements
