### ISSUE TITLE
Socket.io client error

### ISSUE THREAD

**Issue by VedantBang26** [boxug/trape#330]
The client is using an unsupported version of the Socket.IO or Engine.IO protocols (further occurrences of this error will be logged with level INFO)
[2021-08-20 12:39:41,387] ERROR in app: Exception on /get_title [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/dist-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/root/Desktop/trape/core/stats.py", line 97, in home_get_title
    return json.dumps({'status' : 'OK', 'title' : html})
  File "/usr/local/lib/python3.7/dist-packages/flask/json/__init__.py", line 129, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "/usr/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.7/dist-packages/flask/json/__init__.py", line 56, in default
    return super().default(o)
  File "/usr/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type bytes is not JSON serializable

The error I m getting while I track

**Comment by VedantBang26** [comment]
I m using python 3.7

**Comment by cboto314** [comment]
I'm having the same issue. Have you been able to solve?

**Comment by TigerMan1159** [comment]
same problem, when i open control panel link and enter my access key

**Comment by ghost** [comment]
Be aware that by replying/posting you’ll send emails to everyone subscribed to the GitHub repo.

Sent from my iPhone.

On 30 Mar 2022, at 09:41, TigerMan1159 ***@***.***> wrote:

﻿

same problem, when i open control panel link and enter my access key

**Comment by Prince-Hamza** [comment]
same problem here , what are tyhe causes , is there any potential solution ?
