### ISSUE TITLE
ImportError: No module named http.client

### ISSUE THREAD

**Issue by anonymous0305** [boxug/trape#332]
ImportError: No module named http.client
.
.
anyone tell me how to fix this
.
thank you

**Comment by jitesh-eng** [comment]
ImportError: No module named http.client
.
.
anyone tell me how to fix this
.
thank you

**Comment by LicPlatano** [comment]
ImportError: No module named http.client
.
.
anyone tell me how to fix this
.
thank you

**Comment by SirZexx** [comment]
hey when you're running it just use **Python3 instead of Python2** it'll work

**Comment by SirZexx** [comment]
> ImportError: No module named http.client . . anyone tell me how to fix this . thank you

i've posted solution check out if it works

**Comment by TigerMan1159** [comment]
> i've posted solution check out if it works

i have the error when i open control panel link and enter my access key.

The client is using an unsupported version of the Socket.IO or Engine.IO protocols (further occurrences of this error will be logged with level INFO)
[2022-03-30 14:35:36,796] ERROR in app: Exception on /get_title [POST]
Traceback (most recent call last):
  File "/home/tigerman1159/.local/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/tigerman1159/.local/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/tigerman1159/.local/lib/python3.9/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/tigerman1159/.local/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/tigerman1159/.local/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/tigerman1159/trape/core/stats.py", line 97, in home_get_title
    return json.dumps({'status' : 'OK', 'title' : html})
  File "/home/tigerman1159/.local/lib/python3.9/site-packages/flask/json/__init__.py", line 131, in dumps
    return _json.dumps(obj, **kwargs)
  File "/usr/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/tigerman1159/.local/lib/python3.9/site-packages/flask/json/__init__.py", line 50, in default
    return super().default(o)
  File "/usr/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type bytes is not JSON serializable


do you know how to fix it?
