### ISSUE TITLE
ModuleNotFoundError: No module named 'six'

### ISSUE THREAD

**Issue by N17R0-HACKERS** [boxug/trape#338]
$ python3 trape.py -h
Traceback (most recent call last):
  File "/home/kali/trape/trape.py", line 23, in <module>
    from core.utils import utils                  #
  File "/home/kali/trape/core/utils.py", line 21, in <module>
    import requests, json
  File "/usr/lib/python3/dist-packages/requests/__init__.py", line 43, in <module>
    import urllib3
  File "/usr/lib/python3/dist-packages/urllib3/__init__.py", line 11, in <module>
    from . import exceptions
  File "/usr/lib/python3/dist-packages/urllib3/exceptions.py", line 3, in <module>
    from six.moves.http_client import IncompleteRead as httplib_IncompleteRead
ModuleNotFoundError: No module named 'six'
![IMG_20210926_144614](https://user-images.githubusercontent.com/72617624/134801577-61a73567-aee8-4d9f-b39f-1203418d3b15.jpg)

**Comment by kairanaquazi** [comment]
pip install six?
