### ISSUE TITLE
whats issue i cant undesrstand any one help me

### ISSUE THREAD

**Issue by don4848** [boxug/trape#349]
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/aliza/Desktop/trape/core/ngrok.py", line 81, in start_ngrok
    result = subprocess.check_output([str_ngrok, "http", port])
  File "/usr/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['./ngrok', 'http', '8080']' returned non-zero exit status 1.
[x] ERROR: 'URLError' object has no attribute 'message'

**Comment by thindz** [comment]
file "/usr/lib/python3.9/subprocess.py", line 528, in run                                                                                                                                                                                 
    raise CalledProcessError(retcode, process.args,                                                                                                                                                                                         
subprocess.CalledProcessError: Command '['./ngrok', 'http', '8080']' returned non-zero exit status 1.
