### ISSUE TITLE
Getting the below Errorq

### ISSUE THREAD

**Issue by nakulkundra** [boxug/trape#353]
**Getting the following Error when executing "python3 trape.py -h"**
`Traceback (most recent call last):
  File "D:\Git\trape\trape.py", line 23, in <module>
    from core.utils import utils                  #
  File "D:\Git\trape\core\utils.py", line 21, in <module>
    import requests, json
ModuleNotFoundError: No module named 'requests'`

![image](https://user-images.githubusercontent.com/5175294/158373276-6ac29322-0829-41bd-873a-e3655e40d116.png)

**when running on Python 3.10.2**

**Comment by TigerMan1159** [comment]
hmmm i'm not sure, but try to unzip ngrok.zip in the trape folder.

**Comment by rly0nheart** [comment]
@TigerMan1159 No, that's not even close.

@nakulkundra The error clearly tells you what's wrong,  you don't have requests installed.
So before you start trape, make sure you run
``pip install -r requirements.txt``

That should fix it.
