### ISSUE TITLE
PLEASE HELP ME

### ISSUE THREAD

**Issue by TigerMan1159** [boxug/trape#354]
Can anybody teach me how to use this tool?

I need use this tool to track and find scammers who scam my friend.

Honestly i don't understand anything about programming. I only knew that Github is the biggest community of programmer. So i don't know how to use this tool, what application i need to run this tool, or anything else. Maybe I will be able if I study, but for now I need this tool as soon as possible to find this scammer.

Please anyone teach me from the beginning, the basic, step by step. Ooh God

And what specification of my device to be able run this tool? My specification laptop is
Prossesor: Intel Celeron N4000 1.1GHz
OS: Windows 10 Education
RAM: 4 GB
Storage: 1 TB
Graphic Card: iGPU
Browser: Edge, Chrome, and Brave

Let's make the Internet a safer place, let's report.

**Comment by Crewxx** [comment]
You have Microsoft word on your system?

**Comment by TigerMan1159** [comment]
> You have Microsoft word on your system?

Yes

**Comment by TigerMan1159** [comment]
now i can run this tool. But i got some error, when i open control panel link and enter my access key




The client is using an unsupported version of the Socket.IO or Engine.IO protocols (further occurrences of this error will be logged with level INFO)
[2022-03-30 14:12:44,324] ERROR in app: Exception on /get_title [POST]
Traceback (most recent call last):
  File "/home/tigerman1159/.local/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/tigerman1159/.local/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/tigerman1159/.local/lib/python3.9/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/tigerman1159/.local/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/tigerman1159/.local/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/tigerman1159/trape/core/stats.py", line 97, in home_get_title
    return json.dumps({'status' : 'OK', 'title' : html})
  File "/home/tigerman1159/.local/lib/python3.9/site-packages/flask/json/__init__.py", line 131, in dumps
    return _json.dumps(obj, **kwargs)
  File "/usr/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/tigerman1159/.local/lib/python3.9/site-packages/flask/json/__init__.py", line 50, in default
    return super().default(o)
  File "/usr/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type bytes is not JSON serializable





How to fix it?

**Comment by MaratMustafin** [comment]
return json.dumps({'status' : 'OK', 'title' : html}) instead html use 'html'. It's not a fix a problem but program will work.

**Comment by MaratMustafin** [comment]
> now i can run this tool. But i got some error, when i open control panel link and enter my access key
> 
> The client is using an unsupported version of the Socket.IO or Engine.IO protocols (further occurrences of this error will be logged with level INFO) [2022-03-30 14:12:44,324] ERROR in app: Exception on /get_title [POST] Traceback (most recent call last): File "/home/tigerman1159/.local/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app response = self.full_dispatch_request() File "/home/tigerman1159/.local/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request rv = self.handle_user_exception(e) File "/home/tigerman1159/.local/lib/python3.9/site-packages/flask_cors/extension.py", line 165, in wrapped_function return cors_after_request(app.make_response(f(*args, **kwargs))) File "/home/tigerman1159/.local/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request rv = self.dispatch_request() File "/home/tigerman1159/.local/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args) File "/home/tigerman1159/trape/core/stats.py", line 97, in home_get_title return json.dumps({'status' : 'OK', 'title' : html}) File "/home/tigerman1159/.local/lib/python3.9/site-packages/flask/json/**init**.py", line 131, in dumps return _json.dumps(obj, **kwargs) File "/usr/lib/python3.9/json/**init**.py", line 234, in dumps return cls( File "/usr/lib/python3.9/json/encoder.py", line 199, in encode chunks = self.iterencode(o, _one_shot=True) File "/usr/lib/python3.9/json/encoder.py", line 257, in iterencode return _iterencode(o, 0) File "/home/tigerman1159/.local/lib/python3.9/site-packages/flask/json/**init**.py", line 50, in default return super().default(o) File "/usr/lib/python3.9/json/encoder.py", line 179, in default raise TypeError(f'Object of type {o.**class**.**name**} ' TypeError: Object of type bytes is not JSON serializable
> 
> How to fix it?

return json.dumps({'status' : 'OK', 'title' : html}) instead html use 'html'. It's not a fix a problem but program will work.

**Comment by tedol47** [comment]
same issue with me.

**Comment by rbrtjns90** [comment]
I fixed a bunch of these bugs.

https://github.com/rbrtjns90/trape
