### ISSUE TITLE
The client is using an unsupported version of the Socket.IO or Engine.IO protocols (further occurrences of this error will be logged with level INFO)

### ISSUE THREAD

**Issue by fritssasia** [boxug/trape#368]
I need help
I get an error like this when entering the Access key. I also don't get the link to share on the target
`Public lure: .io/www.google.com`

```
`[2022-09-20 21:12:54,064] ERROR in app: Exception on /get_title [POST]
Traceback (most recent call last):
  File "/home/fritssasia/.local/lib/python3.8/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/fritssasia/.local/lib/python3.8/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/fritssasia/.local/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/fritssasia/.local/lib/python3.8/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/fritssasia/.local/lib/python3.8/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/fritssasia/htool/trape/core/stats.py", line 97, in home_get_title
    return json.dumps({'status' : 'OK', 'title' : html})
  File "/home/fritssasia/.local/lib/python3.8/site-packages/flask/json/__init__.py", line 124, in dumps
    return app.json.dumps(obj, **kwargs)
  File "/home/fritssasia/.local/lib/python3.8/site-packages/flask/json/provider.py", line 230, in dumps
    return json.dumps(obj, **kwargs)
  File "/usr/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/fritssasia/.local/lib/python3.8/site-packages/flask/json/provider.py", line 122, in _default
    raise TypeError(f"Object of type {type(o).__name__} is not JSON serializable")
TypeError: Object of type bytes is not JSON serializable`
```

**Comment by Guso-dot** [comment]
Hi -

I get the same error 


[>] Start time: 2022-12-21 - 22:23:38
[?] Do not forget to close Trape, after use. Press Control C

[¡] Waiting for the users to fall...

The client is using an unsupported version of the Socket.IO or Engine.IO protocols (further occurrences of this error will be logged with level INFO)
Process Process-1:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/gurtejbains/Documents/Projects/trape/core/ngrok.py", line 81, in start_ngrok
    result = subprocess.check_output([str_ngrok, "http", port])
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['./ngrok', 'http', '8080']' returned non-zero exit status 1.

**Comment by rbrtjns90** [comment]
I fixed a bunch of these bugs.

https://github.com/rbrtjns90/trape
