### ISSUE TITLE
SQL Insert error for some region

### ISSUE THREAD

**Issue by goRaspy** [boxug/trape#5]
Look like the script do not like people from "Provence Alpes cote d'Azur" region (France)

Trape look to be insane anyway :)

: fd54b
[*] It's his first time
[2017-11-04 00:42:07,868] ERROR in app: Exception on /register [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/root/trape/core/victim.py", line 61, in register
    db.sentences_victim('insert_victim_geo', [victimGeo, vId], 2)
  File "/root/trape/core/db.py", line 94, in sentences_victim
    return self.sql_insert(self.prop_sentences_victim(type, data))
  File "/root/trape/core/db.py", line 39, in sql_insert
    self.cursor.execute(sentence)
OperationalError: near "Azur": syntax error

**Comment by almapro** [comment]
SQL injection in insert_victim_geo!
Wait for them to maybe fix it with prepare statement if that's available in python :/

**Comment by st4nn** [comment]
@goRaspy @almapro Thanks guys for commenting, I've pushed a new commit, I hope solved the bug.

Thanks again and Happy Hack

**Comment by goRaspy** [comment]
![image](https://user-images.githubusercontent.com/10080460/32417381-1b28d514-c259-11e7-8371-e31d7b112730.png)

Now, works like a charm. Many thanks

**Comment by jofpin** [comment]
Thanks to you, enjoy it and share it with your friends.
